import { Toaster } from "@/components/ui/sonner";
import "./globals.css";



export const metadata = {
  title: "Deal Drop",
  description: "Generated by R.D.Parmar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}
        <Toaster richColors />
      </body>
    </html>
  );
}
